services:
  api:
    build: 
        context: .
        dockerfile: src/api/Dockerfile
    image: api-web-site
    container_name: api-web-site
    env_file:
      - .dev.env
    volumes:
      - ./src/api/app:/project/src/api/app
      - ./src/api/migrations:/project/src/api/migrations
      - ./certs:/certs
    ports:
      - "8000:8000"

  web:
    image: nginx:alpine
    volumes:
      - ./src/frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - api