"""empty message

Revision ID: 55dcac349bff
Revises: 
Create Date: 2026-04-27 02:30:30.565067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55dcac349bff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('boss', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('roots', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'roots')
    op.drop_column('employees', 'boss')
    # ### end Alembic commands ###
