"""empty message

Revision ID: b0cd701102d3
Revises: 55dcac349bff
Create Date: 2026-04-27 21:36:53.650540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0cd701102d3'
down_revision: Union[str, Sequence[str], None] = '55dcac349bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make_sales', sa.Boolean(), nullable=False),
    sa.Column('add_categories', sa.Boolean(), nullable=False),
    sa.Column('add_products', sa.Boolean(), nullable=False),
    sa.Column('redact_products', sa.Boolean(), nullable=False),
    sa.Column('add_jobs', sa.Boolean(), nullable=False),
    sa.Column('add_boss', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('root_id', sa.Integer(), nullable=False))
    op.drop_column('jobs', 'roots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('roots', sa.INTEGER(), nullable=False))
    op.drop_column('jobs', 'root_id')
    op.drop_table('roots')
    # ### end Alembic commands ###
