"""empty message

Revision ID: db3f4a6aa279
Revises: b0cd701102d3
Create Date: 2026-04-27 21:56:31.840728

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "db3f4a6aa279"
down_revision: Union[str, Sequence[str], None] = "b0cd701102d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs") as batch_op:
        batch_op.create_foreign_key("fk_jobs_root_id", "roots", ["root_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs") as batch_op:
        batch_op.drop_constraint("fk_jobs_root_id", type_="foreignkey")
    # ### end Alembic commands ###
